version: '1.0'

services:
  predictive-maintenance-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: predictive-maintenance-api
    ports:
      - "8000:8000"

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # Network for future services (monitoring, database, etc.)
    networks:
      - predictive-maintenance

networks:
  predictive-maintenance:
    driver: bridge 